config/routes.rb
RedditClone::Application.routes.draw do
  resources :users, :only => [:new, :create, :show]
  resource :session, :only => [:new, :create, :destroy]
  resources :subs
  resources :links, :only => [:new, :create, :show, :edit, :update] do
    resources :comments, :only => [:new, :create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :parent_comment_id

  validates :text, :presence => true

  belongs_to :user
  belongs_to :parent_comment, :class_name => "Comment"
  belongs_to :link

  has_many :child_comments, :foreign_key => :parent_comment_id, :class_name => "Comment"
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :text, :title, :url, :sub_ids

  validates :title, :url, :presence => true
  validates :subs, :presence => true

  has_many :link_subs, :inverse_of => :link

  has_many :subs, :through => :link_subs, :source => :sub, :inverse_of => :links

  belongs_to :user, :inverse_of => :links

  has_many :comments


  def comments_by_parent_id
    hash = Hash.new { |h, k| h[k] = [] }

    self.comments.includes(:user).each do |comment|
      hash[comment.parent_comment_id] << comment
    end

    hash
  end
end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  # attr_accessible :link_id, :sub_id
  belongs_to :link, :inverse_of => :link_subs
  belongs_to :sub, :inverse_of => :link_subs
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :name

  belongs_to :moderator, :class_name => "User", :inverse_of => :subs
  has_many :link_subs, :inverse_of => :sub
  has_many :links, :through => :link_subs, :source => :link, :inverse_of => :subs

  validates :name, :presence => true, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password

  validates :email, :session_token, :presence => true, :uniqueness => true
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  before_validation { self.session_token = SecureRandom.urlsafe_base64(16) }

  has_many :subs, :foreign_key => :moderator_id, :inverse_of => :moderator

  has_many :links, :inverse_of => :user

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    return nil unless user

    user.is_password?(password) ? user : nil
  end


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include SubsHelper
  include LinksHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    # @comment.parent_comment_id = params[:parent_comment_id]

    @link = Link.find(params[:link_id])
    @parent_comment = Comment.find(params[:parent_comment_id])

    render :new
  end

  def create
    link = Link.find(params[:link_id])
    @comment = link.comments.build(params[:comment])

    @comment.user_id = current_user.id

    if @comment.save
      redirect_to link
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :link_belongs_to_current_user, :only => [:edit, :update, :destroy]
  def new
    @link = Link.new
    render :new
  end

  def create
    @link = Link.new(params[:link])

    if @link.save
      redirect_to @link
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    render :edit
  end

  def update
    @link = Link.find(params[:id])

    if @link.update_attributes(params[:link])
      redirect_to @link
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  def show
    @link = Link.find(params[:id])
    render :show
  end


  private
    def link_belongs_to_current_user
      @link = Link.find(params[:id])
      unless current_user_owns_link?(@link)
        flash.now[:error] = "This link doesn't belong to you"
        render :show
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if !user.nil?
      login!(user)
      redirect_to user
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update]
  before_filter :sub_belongs_to_current_user, :only => [:edit, :update]

  def new
    @sub = Sub.new
    5.times do
      @sub.links.build
    end

    render :new
  end

  def create
    @sub = current_user.subs.build(params[:sub])

    params[:links].values.each do |link_params|
      next if link_params.all? { |k, v| v == "" }
      @sub.links.build(link_params)
    end

    if @sub.save
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      (5-@sub.links.length).times do
        @sub.links.build
      end
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(params[:sub])
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.includes(:links).find(params[:id])
    render :show
  end


  private
    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_session_url # halts request cycle
      end
    end

    def sub_belongs_to_current_user
      @sub = Sub.find(params[:id])
      unless current_user_moderates_sub?(@sub)
        flash.now[:error] = "This sub doesn't belong to you"
        render :show
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login!(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def current_user_owns_link?(link)
    current_user != nil && current_user.id == link.user_id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login!(user)
    session[:session_token] = user.session_token
    current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/helpers/subs_helper.rb
module SubsHelper
  def current_user_moderates_sub?(sub)
    current_user != nil && sub.moderator_id == current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= comment.text %><br>
<%= comment.created_at %> by <%= comment.user.email %>
<% comments_by_parent_id[comment.id].each do |com| %>
  <ul>
    <%= render "comments/comment", :comment => com, :comments_by_parent_id => comments_by_parent_id %>
  </ul>
<% end %>

app/views/comments/new.html.erb
<h1>Add Comment</h1>

Link:
<%= @link.url %><br>
<%= @link.text %>

<% if @parent_comment %>
Parent Comment:
<%= @parent_comment.text %>
<% end %>


Comment:
<form action="<%= link_comments_url(@link) %>" method="post">
  <%= render "shared/errors" %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @parent_comment.id if @parent_comment %>">

  <label for="comment_text">Comment</label>
  <textarea id="comment_text" name="comment[text]"><%= @comment.text %></textarea>
  <br>

  <input type="submit" value="Add comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:error] %>
  <div id="global_error">
    <%= flash[:error] %>
  </div>
  <% end %>

  <% if logged_in? %>
    <%= link_to current_user.email, current_user %> |
    <%= button_to "Log out", session_url, :method => :delete %>
  <% else %>
  <%= button_to "Log in", new_session_url, :method => :get %> |
  <%= button_to "Sign up", new_user_url, :method => :get %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/links/_form_fields.html.erb
<label for="link_title">Title</label>
<input id="link_title" name="link[title]" value="<%= @link.title %>">
<br>

<label for="link_url">Url</label>
<input id="link_url" name="link[url]" value="<%= @link.url %>">
<br>

<label for="link_text">Text</label>
<textarea id="link_text" name="link[text]"><%= @link.text %></textarea>
<br><br>

<input type="hidden" name="link[sub_ids][]" value="">
<% Sub.all.each do |sub| %>
  <input type="checkbox"
         id="link_sub_ids_<%= sub.id %>"
         name="link[sub_ids][]"
         value="<%= sub.id %>"
         <%= "checked" if @link.subs.include?(sub) %>>
  <label for="link_sub_ids_<%= sub.id %>"><%= sub.name %></label>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<form action="<%= link_url(@link) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
  <%= render "shared/errors" %>

  <%= render "form_fields" %>
  <br>

  <input type="submit" value="Edit link">
</form>

app/views/links/new.html.erb
<form action="<%= links_url %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= render "shared/errors" %>
  <%= render "form_fields" %>

  <p><input type="submit" value="Create Link"></p>
</form>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>
<% if current_user_owns_link?(@link) %>
<div>
  <%= link_to "Edit", edit_link_url(@link) %>
</div>
<% end %>


<a href="<%= @link.url %>" target="blank"><%= @link.url %></a>

<p>
<%= @link.text %>
</p>

Comments:

<% comments_by_parent_id = @link.comments_by_parent_id %>
<ul>
  <% comments_by_parent_id[nil].each do |comment| %>
    <%= render "comments/comment", :comment => comment, :comments_by_parent_id => comments_by_parent_id %>
  <% end %>
</ul>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

app/views/subs/edit.html.erb
<h1>Edit sub</h1>
<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">

  <%= render "shared/errors" %>

  <label for="sub_name">Name</label>
  <input type="text" id="sub_name" name="sub[name]" value="<%= @sub.name %>">
  <br><br>

  <input type="submit" value="Edit sub">
</form>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= render "shared/errors" %>

  <label for="sub_name">Name</label>
  <input type="text" id="sub_name" name="sub[name]" value="<%= @sub.name %>">
  <br><br>

  <label for="links">Links</label>
  <br>

  <% @sub.links.each_with_index do |link, index| %>
  <label for="links_<%= index %>_title">Title</label>
  <input id="links_<%= index %>_title" name="links[<%= index %>][title]" value="<%= link.title %>">
  <br>

  <label for="links_<%= index %>_url">Url</label>
  <input id="links_<%= index %>_url" name="links[<%= index %>][url]" value="<%= link.url %>">
  <br>

  <label for="links_<%= index %>_text">Text</label>
  <textarea id="links_<%= index %>_text" name="links[<%= index %>][text]"><%= link.text %></textarea>
  <br><br>
  <% end %>

  <input type="submit" value="Create sub">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1> |
<% if current_user_moderates_sub?(@sub) %>
<%= link_to "Edit", edit_sub_url(@sub) %>
<% end %>

<ul>
  <% @sub.links.each do |link| %>
  <li>
    <%= link_to link.title, link %>
  </li>
  <% end %>
</ul>

app/views/users/_form_fields.html.erb
<%= render "shared/errors" %>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label for="user_email">Email</label>
<input type="text" id="user_email" name="user[email]" value="<%= @user.email %>">

<label for="user_password">Password</label>
<input type="password" id="user_password" name="user[password]">

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post" accept-charset="utf-8">
  <%= render "form_fields" %>

  <p><input type="submit" value="Sign up"></p>
</form>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>